#!/bin/bash

sudo find /home/fram/vsescri -name "*jpg" | while read filename
do
        bash script_1  $filename &

done
# амперсант помогает вайл не ждать пока закончиться работа скрипта1 и запускает их пораленьно

